Repository pubnub/javascript, pull requests merged in 2023-06, with the labels that each got.

#324 clen1290/add optional param in setState for setting state through heartbeat endpoint
  .github/CODEOWNERS
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/config.js
  lib/core/components/subscription_manager.js
  package-lock.json
  package.json
  src/core/components/config.js
  src/core/components/subscription_manager.js
  test/integration/endpoints/presence.test.js
Labels: status: done

#325 build(s3): fix upload of artifacts to s3
  .github/workflows/release.yml
Labels: status: done, priority: high

#327 Update version and version bump regexp
  .github/workflows/release/versions.json
  .pubnub.yml
Labels: status: done, type: documentation, priority: medium
