Repository pubnub/javascript, pull requests merged in 2024-06, with the labels that each got.

#378 Fix automatic `heartbeatInterval` set
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/core/interfaces/configuration.js
  package-lock.json
  package.json
  src/core/components/configuration.ts
  src/core/interfaces/configuration.ts
  test/integration/components/config.test.ts
Labels: status: done, priority: medium, type: fix

#379 Fix `sort` options serialization
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/core/endpoints/objects/channel/get_all.js
  lib/core/endpoints/objects/member/get.js
  lib/core/endpoints/objects/member/set.js
  lib/core/endpoints/objects/membership/get.js
  lib/core/endpoints/objects/membership/set.js
  lib/core/endpoints/objects/uuid/get_all.js
  package.json
  src/core/components/configuration.ts
  src/core/endpoints/objects/channel/get_all.ts
  src/core/endpoints/objects/member/get.ts
  src/core/endpoints/objects/member/set.ts
  src/core/endpoints/objects/membership/get.ts
  src/core/endpoints/objects/membership/set.ts
  src/core/endpoints/objects/uuid/get_all.ts
Labels: status: done, priority: medium, type: fix

#381 fix: dependabot security alert related to dev-deps
  package-lock.json
  package.json
Labels: status: done, priority: low, type: build

#385 fix: `Subscription` entity's `subscribe()` signature to accept timetoken
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/entities/SubscribeCapable.js
  lib/types/entities/SubscribeCapable.d.ts
  lib/types/entities/commonTypes.d.ts
  package-lock.json
  package.json
  src/core/components/configuration.ts
  src/entities/SubscribeCapable.ts
  src/entities/commonTypes.ts
  test/integration/endpoints/subscribe.test.ts
Labels: status: done, type: bug, priority: high
