Repository pubnub/javascript, pull requests merged in 2025-01, with the labels that each got.

#427 fix: issue of parsing response for here_now
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/core/endpoints/presence/here_now.js
  package.json
  src/core/components/configuration.ts
  src/core/endpoints/presence/here_now.ts
  test/integration/endpoints/presence.test.ts
Labels: type: bug, type: fix

#430 Add file upload and download timeout configuration
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/core/interfaces/configuration.js
  lib/core/pubnub-common.js
  lib/transport/middleware.js
  lib/types/index.d.ts
  package.json
  src/core/components/configuration.ts
  src/core/interfaces/configuration.ts
  src/core/pubnub-common.ts
  src/transport/middleware.ts
  test/integration/endpoints/subscribe.test.ts
Labels: status: done, priority: high, type: feature

#434 Fix long-poll request cancellation
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/react_native/index.js
  lib/transport/web-react-native-transport.js
  package.json
  src/core/components/configuration.ts
  src/react_native/index.ts
  src/transport/web-react-native-transport.ts
  src/web/index.ts
Labels: status: done, priority: high, type: fix
