Repository pubnub/javascript, pull requests merged in 2025-09, with the labels that each got.

#472 test: add missing unit and integration test
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/endpoints/presence/get_state.js
  lib/core/endpoints/presence/heartbeat.js
  lib/core/endpoints/presence/set_state.js
  package-lock.json
  src/core/endpoints/presence/get_state.ts
  src/core/endpoints/presence/heartbeat.ts
  src/core/endpoints/presence/set_state.ts
  src/core/pubnub-common.ts
  test/integration/endpoints/channel_groups.test.ts
  test/integration/endpoints/fetch_messages.test.ts
  test/integration/endpoints/message_actions.test.ts
  test/integration/endpoints/objects/channel.test.ts
  test/integration/endpoints/presence_errors.test.ts
  test/unit/access_manager/access_manager_grant_token.test.ts
  test/unit/access_manager/access_manager_revoke_token.test.ts
  test/unit/app_context/channel_objects_get.test.ts
  test/unit/app_context/channel_objects_get_all.test.ts
  test/unit/app_context/channel_objects_remove.test.ts
  test/unit/app_context/channel_objects_set.test.ts
  test/unit/app_context/membership_objects_get.test.ts
  test/unit/app_context/membership_objects_remove.test.ts
  test/unit/app_context/membership_objects_set.test.ts
  test/unit/chanel_groups/channel_groups_delete_group.test.ts
  test/unit/chanel_groups/channel_groups_list_channels.test.ts
  test/unit/chanel_groups/channel_groups_list_groups.test.ts
  test/unit/chanel_groups/channel_groups_remove_channels.test.ts
  test/unit/chanel_groups/uuid_objects_get.test.ts
  test/unit/chanel_groups/uuid_objects_get_all.test.ts
  test/unit/chanel_groups/uuid_objects_remove.test.ts
  test/unit/chanel_groups/uuid_objects_set.test.ts
  test/unit/fetch_messages/fetch_messages.test.ts
  test/unit/message_actions/message_actions.test.ts
  test/unit/presence/presence_get_state.test.ts
  test/unit/presence/presence_heartbeat.test.ts
  test/unit/presence/presence_here_now.test.ts
  test/unit/presence/presence_leave.test.ts
  test/unit/presence/presence_set_state.test.ts
  test/unit/presence/presence_where_now.test.ts
  test/unit/publish/publish.test.ts
  test/unit/push_notification/push_add_channels.test.ts
  test/unit/push_notification/push_base.test.ts
  test/unit/push_notification/push_list_channels.test.ts
  test/unit/push_notification/push_remove_channels.test.ts
  test/unit/push_notification/push_remove_device.test.ts
  test/unit/test-utils.ts
Labels: status: done, priority: low, type: test

#477 Add `limit` and `offset` parameters
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  package.json
  src/core/components/configuration.ts
Labels: status: done, priority: medium, type: feature

#478 restore legacy crypto module support for React Native target
  lib/crypto/modules/LegacyCryptoModule.js
  lib/react_native/index.js
  package-lock.json
  src/crypto/modules/LegacyCryptoModule.ts
  src/react_native/configuration.ts
  src/react_native/index.ts
  test/integration/components/legacyCryptoModule.test.ts
Labels: status: done, priority: medium, type: refactor

#479 fix: presence event engine internal state sync
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  lib/core/components/configuration.js
  lib/core/endpoints/presence/here_now.js
  lib/core/pubnub-common.js
  lib/crypto/modules/LegacyCryptoModule.js
  lib/event-engine/presence/presence.js
  lib/react_native/index.js
  lib/types/index.d.ts
  package-lock.json
  package.json
  src/core/components/configuration.ts
  src/core/endpoints/presence/here_now.ts
  src/core/pubnub-common.ts
  src/core/types/api/presence.ts
  src/crypto/modules/LegacyCryptoModule.ts
  src/event-engine/presence/presence.ts
  src/react_native/configuration.ts
  src/react_native/index.ts
  test/integration/components/legacyCryptoModule.test.ts
  test/integration/endpoints/fetch_messages.test.ts
  test/integration/endpoints/presence.test.ts
  test/unit/event_engine_presence.test.ts
Labels: status: done, priority: high
