Repository pubnub/javascript, pull requests merged in 2025-07, with the labels that each got.

#463 test: subscription/presence behavior with shared-worker
  .mocharc.json
  karma/shared-worker.config.js
  package.json
  test/integration/shared-worker/shared-worker.test.ts
Labels: status: in progress, priority: high, type: test

#461 Fix rapid subscribe aggregate
  .mocharc.json
  .prettierrc
  .pubnub.yml
  CHANGELOG.md
  README.md
  dist/web/pubnub.js
  dist/web/pubnub.min.js
  dist/web/pubnub.worker.js
  dist/web/pubnub.worker.min.js
  karma/shared-worker.config.js
  lib/core/components/configuration.js
  lib/core/constants/categories.js
  lib/core/pubnub-common.js
  lib/entities/subscription-base.js
  lib/entities/subscription-set.js
  lib/entities/subscription.js
  lib/errors/pubnub-api-error.js
  lib/types/index.d.ts
  package-lock.json
  package.json
  src/core/components/configuration.ts
  src/core/constants/categories.ts
  src/core/pubnub-common.ts
  src/entities/subscription-base.ts
  src/entities/subscription-set.ts
  src/entities/subscription.ts
  src/errors/pubnub-api-error.ts
  src/transport/subscription-worker/subscription-worker-middleware.ts
  src/transport/subscription-worker/subscription-worker.ts
  src/web/index.ts
  test/integration/shared-worker/shared-worker.test.ts
Labels: status: in progress, priority: high, type: fix

#466 Use Amazon GHA to setup AWS CLI credentials
  .github/workflows/release.yml
Labels: status: done, priority: medium, type: build
